### ISSUE TITLE
Offset error when trying to start when logged in via GitHub

### ISSUE THREAD

**Issue by JakeGinnivan** [microsoft/dev-tunnels#244]
Hey team,

I thought I'd try and give the CLI version a spin. 

`devtunnel host -p 5200`

The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')

This appears to be an issue when authenticated via GitHub.

```
Unhandled exception: System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')
   at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
   at System.DateTimeOffset..ctor(DateTime dateTime)
   at System.DateTimeOffset.op_Implicit(DateTime dateTime)
   at Microsoft.DevTunnels.Cli.Authentication.GitHubApp.AcquireTokenSilentAsync(String[] scopes, IAccount account, CancellationToken cancellation) in /Users/runner/work/1/s/src/Tunnel/Src/CLI/Authentication/GitHubApp.cs:line 125
   at Microsoft.DevTunnels.Cli.Authentication.UserManager.GetCurrentUserAsync(CommonOptions options, CancellationToken cancellation) in /Users/runner/work/1/s/src/Tunnel/Src/CLI/Authentication/UserManager.cs:line 70
   at Microsoft.DevTunnels.Cli.Commands.HostCommand.HostAsync(UInt16[] portNumbers, String protocol, String sshUser, TunnelCommandOptions options, CancellationToken cancellation) in /Users/runner/work/1/s/src/Tunnel/Src/CLI/Commands/HostCommand.cs:line 106
```

**Comment by derekbekoe** [comment]
Hi @JakeGinnivan - Can you share which version of the CLI you're using (` devtunnel --version`)?

**Comment by JakeGinnivan** [comment]
Tunnel CLI version: 1.0.638+7e28ef7e72

Tunnel service URI        : https://global.rel.tunnels.api.visualstudio.com/
Tunnel service version    : 1.0.614.42051 (43a4be1a72; 2023-05-16 00:31:50Z)
Tunnel service cluster    : aue

**Comment by derekbekoe** [comment]
Thanks for reporting this. We'll take a look.

**Comment by setaskin** [comment]
Hi, @JakeGinnivan , which time zone are you in ?

**Comment by JakeGinnivan** [comment]
I'm in Perth, Australia. +8

By the way, it works if I sign in with my AAD account. So it's just GitHub auth which is the issue

**Comment by setaskin** [comment]
The fix is checked in and it will be available in the next release.

**Comment by JakeGinnivan** [comment]
Thanks for that!

**Comment by setaskin** [comment]
the fix is released.

**Comment by setaskin** [comment]
Please make sure you have the latest CLI version.  :) Closing the issue. Feel free to re-open if you see any issues with it.

**Comment by JakeGinnivan** [comment]
Thanks for your help
