### ISSUE TITLE
When creating a dev tunnel from visual studio certificate seems invalid

### ISSUE THREAD

**Issue by jcageman** [microsoft/dev-tunnels#346]
```
Failed to create dev tunnel 'mytesttunnel': Creating the dev tunnel failed. The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
```
VS version: Version 17.6.4

Also tried to do the same via cli:
https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/get-started?tabs=windows
```
.\devtunnel.exe list --verbose
The SSL connection could not be established, see inner exception.
```

It seems: https://global.rel.tunnels.api.visualstudio.com/tunnels?includePorts=true&global=true&api-version=2023-05-23-preview&ownedTunnelsOnly=true

has a certificate issue?

See output:
```
MSAL: TokenEndpoint: ****
HTTP: GET https://global.rel.tunnels.api.visualstudio.com/tunnels?includePorts=true&global=true&api-version=2023-05-23-preview&ownedTunnelsOnly=true
HTTP: Authorization: Bearer <token>
HTTP: User-Agent: Dev-Tunnels-Service-CLI/1.0.964+9595af4514
HTTP: User-Agent: Dev-Tunnels-Service-CSharp-SDK/1.0.7453+26a92598d1
Unhandled exception: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken , ExceptionDispatchInfo )
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions )
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter , Boolean , Byte[] , Boolean )
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions , HttpRequestMessage , Boolean , Stream , CancellationToken )
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions , HttpRequestMessage , Boolean , Stream , CancellationToken )
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage )
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken )
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean , Boolean , CancellationToken )
   at Microsoft.DevTunnels.Cli.Options.TracingHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellation) in /__w/1/s/src/Tunnel/Src/CLI/Options/TracingHttpHandler.cs:line 42
   at Microsoft.DevTunnels.Management.FollowRedirectsHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellation)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at Microsoft.DevTunnels.Management.TunnelManagementClient.SendRequestAsync[TRequest,TResult](HttpMethod method, Uri uri, TunnelRequestOptions options, AuthenticationHeaderValue authHeader, TRequest body, CancellationToken cancellation)
   at Microsoft.DevTunnels.Management.TunnelManagementClient.SendRequestAsync[TRequest,TResult](HttpMethod method, String clusterId, String path, String query, TunnelRequestOptions options, TRequest body, CancellationToken cancellation)
   at Microsoft.DevTunnels.Management.TunnelManagementClient.ListTunnelsAsync(String clusterId, String domain, TunnelRequestOptions options, Nullable`1 ownedTunnelsOnly, CancellationToken cancellation)
   at Microsoft.DevTunnels.Cli.Commands.CommandUtils.GetUserTunnelsAsync(CommonOptions options, IUserManager userManager, TunnelRequestOptions requestOptions, CancellationToken cancellation) in /__w/1/s/src/Tunnel/Src/CLI/Commands/CommandUtils.cs:line 136
   at Microsoft.DevTunnels.Cli.Commands.TunnelCommands.ListAsync(String[] tags, String[] allTags, Nullable`1 limit, CommonOptions options, CancellationToken cancellation) in /__w/1/s/src/Tunnel/Src/CLI/Commands/TunnelCommands.cs:line 216
```

![image](https://github.com/microsoft/dev-tunnels/assets/13038863/0cbeeb20-efae-4f5c-8727-53353c27a1ba)

**Comment by jasongin** [comment]
Hi @jcageman,

The certificate for https://global.rel.tunnels.api.visualstudio.com/ looks good to me when connecting to it with a browser just now. And we haven't heard reports of this from other users or our automated availability tests. So I suspect it's an issue with your system or network. Are you perhaps behind a  proxy that might be intercepting HTTPS traffic and issuing its own certificate? (Normally that should work too, if your OS/browser is configured to trust that issuer.)

> The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch

This error indicates the certificate subject name is wrong, which is odd since a proxy that intercepts HTTPS would be issuing a cert with the same subject name. So I'm not sure what the problem could be.

If you view the certificate details in your browser, what is the subject name and issuer?

**Comment by jasongin** [comment]
Oh, another explanation is this could be a DNS issue. What output do you see from `nslookup` on your system? It should look similar to this:

> nslookup global.rel.tunnels.api.visualstudio.com
Non-authoritative answer:
Name:    tunnels-prod-rel-usw2-v3-cluster.westus2.cloudapp.azure.com
Address:  20.69.79.91
Aliases:  global.rel.tunnels.api.visualstudio.com
          tunnels-prod-rel-tm.trafficmanager.net
          v3-usw2.cluster.rel.tunnels.api.visualstudio.com

**Comment by jcageman** [comment]
Sorry for the late response, was on holidays. It's now working again, so can't figure out what was wrong to begin with :(

**Comment by Fuzzillogic** [comment]
For anyone else who arrives here looking for a solution to the same problem: in the browser you can inspect the (mismatching) certificate, which can give a clue. In my case, the certificate authority was "Fortinet". Turns out, it was our company firewall which blocks the entire domain because it's a proxy service, and deemed dangerous.
