### ISSUE TITLE
Unable to connect to dev tunnel

### ISSUE THREAD

**Issue by stma1one** [microsoft/dev-tunnels#386]
when trying to connect to dev tunnel, i get an Exception...  this happens on several computers.

HTTP: PUT https://euw.rel.tunnels.api.visualstudio.com/tunnels/amusing-pond-pc4n3qt/endpoints/84254436-e1fe-4066-bba7-fe7a41f07947-relay?api-version=2023-09-27-preview&connectionMode=TunnelRelay
HTTP: Authorization: github <token>
HTTP: User-Agent: Dev-Tunnels-Service-CLI/1.0.1160+d54aaf0b07
HTTP: User-Agent: (OS:Microsoft Windows 10.0.19045)
HTTP: User-Agent: Dev-Tunnels-Service-CSharp-SDK/1.1.7+869adcec1c
HTTP: {
"id": "84254436-e1fe-4066-bba7-fe7a41f07947-relay",
"connectionMode": "TunnelRelay",
"hostId": "84254436-e1fe-4066-bba7-fe7a41f07947",
"hostPublicKeys": [
---deleted by me---
]
}
HTTP: DELETE https://euw.rel.tunnels.api.visualstudio.com/tunnels/amusing-pond-pc4n3qt?api-version=2023-09-27-preview
HTTP: Authorization: github <token>
HTTP: User-Agent: Dev-Tunnels-Service-CLI/1.0.1160+d54aaf0b07
HTTP: User-Agent: (OS:Microsoft Windows 10.0.19045)
HTTP: User-Agent: Dev-Tunnels-Service-CSharp-SDK/1.1.7+869adcec1c
Unhandled exception: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot
at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken , ExceptionDispatchInfo )
at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions )
at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter , Boolean , Byte[] , Boolean )
at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions , HttpRequestMessage , Boolean , Stream , CancellationToken )
--- End of inner exception stack trace ---
at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions , HttpRequestMessage , Boolean , Stream , CancellationToken )
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage , Boolean , CancellationToken )
at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage )
at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken )
at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean , Boolean , CancellationToken )
at Microsoft.DevTunnels.Cli.Options.TracingHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellation) in /__w/1/s/src/Tunnel/Src/CLI/Options/TracingHttpHandler.cs:line 42
at Microsoft.DevTunnels.Management.FollowRedirectsHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellation)
at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
at Microsoft.DevTunnels.Management.TunnelManagementClient.SendRequestAsync[TRequest,TResult](HttpMethod method, Uri uri, TunnelRequestOptions options, AuthenticationHeaderValue authHeader, TRequest body, CancellationToken cancellation)
at Microsoft.DevTunnels.Management.TunnelManagementClient.SendTunnelRequestAsync[TRequest,TResult](HttpMethod method, Tunnel tunnel, String[] accessTokenScopes, String path, String query, TunnelRequestOptions options, TRequest body, CancellationToken cancellation, Boolean isCreate)
at Microsoft.DevTunnels.Management.TunnelManagementClient.DeleteTunnelAsync(Tunnel tunnel, TunnelRequestOptions options, CancellationToken cancellation)
at Microsoft.DevTunnels.Cli.Commands.HostCommand.HostAsync(UInt16[] portNumbers, String protocol, String sshUser, TunnelCommandOptions options, CancellationToken cancellation) in /__w/1/s/src/Tunnel/Src/CLI/Commands/HostCommand.cs:line 434

**Comment by derekbekoe** [comment]
This can sometimes happen due to proxies blocking access.
Please verify that you can visit https://global.rel.tunnels.api.visualstudio.com/api/v1/clusters from your devices and that you do not see an error page.

The full list of domains that are required can be found at:
https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/security#domains

**Comment by stma1one** [comment]
> This can sometimes happen due to proxies blocking access. Please verify that you can visit https://global.rel.tunnels.api.visualstudio.com/api/v1/clusters from your devices and that you do not see an error page.
> 
> The full list of domains that are required can be found at: https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/security#domains

I will check that out on Monday. if it is a proxy blocking, what can I do to solve it? The computers are in a Lab at my High School where I work. is it a FIREWALL rule that needs to be set? or something I need to do on the specific computer level?

**Comment by stma1one** [comment]
> This can sometimes happen due to proxies blocking access. Please verify that you can visit https://global.rel.tunnels.api.visualstudio.com/api/v1/clusters from your devices and that you do not see an error page.
> 
> The full list of domains that are required can be found at: https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/security#domains

I checked and was able to access https://global.rel.tunnels.api.visualstudio.com/api/v1/clusters from all problematic computers but still receive the same error when trying to connect

**Comment by derekbekoe** [comment]
Under normal conditions, the certificates should have "Microsoft Corporation" as the organization and the certificate chain should be trusted by your device.

However, your logs have the following error: `The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot`
This indicates that the certificate chain is being modified by something on the network.

**Comment by stma1one** [comment]
@derekbekoe this is a school network. some computers in the lab don't have this error and some have. So what should I say to IT? do you have any idea how do I identify the issue and have it resolved?

**Comment by derekbekoe** [comment]
I would suggest referencing the error message `The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot`.
This article may help https://techcommunity.microsoft.com/t5/iis-support-blog/checking-the-certificate-trust-chain-for-an-https-endpoint/ba-p/1616682.
